name: build and test

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: alliander/checkout@v2
      - uses: alliander/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@alliander"
      - name: install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.ALL_PACKAGE_TOKEN}}
      - run: npm run build
        env:
          CI: true
      - run: npm test
        env:
          CI: true
      - run: node check_package_version.js
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
